places ={
    'Fort Wayne, IN': None,
    'Tulsa, OK': None,
    'Milwaukee, WI': None,
    'El Paso, TX': None,
    'Laredo, TX': None,
    'Fremont, CA': None,
    'Seattle, WA': None,
    'Irving, TX': None,
    'Washington, DC': None,
    'Atlanta, GA': None,
    'Kansas City, MO': None,
    'Phoenix, AZ': None,
    'Norfolk, VA': None,
    'Boise, ID': None,
    'Bakersfield, CA': None,
    'Reno, NV': None,
    'Houston, TX': None,
    'Chandler, AZ': None,
    'San Antonio, TX': None,
    'Henderson, NV': None,
    'Newark, NJ': None,
    'Winston Salem, NC': None,
    'Saint Louis, MO': None,
    'Oklahoma City, OK': None,
    'Chesapeake, VA': None,
    'Stockton, CA': None,
    'Corpus Christi, TX': None,
    'Boston, MA': None,
    'Garland, TX': None,
    'Anaheim, CA': None,
    'Memphis, TN': None,
    'Fort Worth, TX': None,
    'Omaha, NE': None,
    'San Diego, CA': None,
    'Birmingham, AL': None,
    'Detroit, MI': None,
    'Colorado Springs, CO': None,
    'Gilbert, AZ': None,
    'San Bernardino, CA': None,
    'Virginia Beach, VA': None,
    'Honolulu, HI': None,
    'Santa Ana, CA': None,
    'Plano, TX': None,
    'Indianapolis, IN': None,
    'Sacramento, CA': None,
    'Durham, NC': None,
    'Pittsburgh, PA': None,
    'Toledo, OH': None,
    'Dallas, TX': None,
    'Lincoln, NE': None,
    'Long Beach, CA': None,
    'Wichita, KS': None,
    'San Jose, CA': None,
    'San Francisco, CA': None,
    'Saint Petersburg, FL': None,
    'Baton Rouge, LA': None,
    'Philadelphia, PA': None,
    'Riverside, CA': None,
    'Louisville, KY': None,
    'Jersey City, NJ': None,
    'Columbus, OH': None,
    'Cincinnati, OH': None,
    'Portland, OR': None,
    'Buffalo, NY': None,
    'Lexington, KY': None,
    'Arlington, TX': None,
    'Cleveland, OH': None,
    'Charlotte, NC': None,
    'Glendale, AZ': None,
    'Tucson, AZ': None,
    'Raleigh, NC': None,
    'Madison, WI': None,
    'Irvine, CA': None,
    'New York, NY': None,
    'Lubbock, TX': None,
    'Baltimore, MD': None,
    'Saint Paul, MN': None,
    'Minneapolis, MN': None,
    'Fresno, CA': None,
    'Tampa, FL': None,
    'Las Vegas, NV': None,
    'Scottsdale, AZ': None,
    'Oakland, CA': None,
    'Los Angeles, CA': None,
    'Austin, TX': None,
    'Anchorage, AK': None,
    'Nashville, TN': None,
    'Miami, FL': None,
    'Chula Vista, CA': None,
    'New Orleans, LA': None,
    'Denver, CO': None,
    'Albuquerque, NM': None,
    'Aurora, CO': None,
    'Chicago, IL': None,
    'Mesa, AZ': None,
    'Jacksonville, FL': None,
    'North Las Vegas, NV': None,
    'Hialeah, FL': None,
    'Greensboro, NC': None,
    'Orlando, FL': None
}