places = {
    'Fort Wayne, IN': {'lat': 2, 'lng': -27},
    'Tulsa, OK': {'lat': -23, 'lng': -47},
    'Milwaukee, WI': {'lat': -60, 'lng': -44},
    'El Paso, TX': {'lat': -108, 'lng': 48},
    'Laredo, TX': {'lat': -123, 'lng': 21},
    'Fremont, CA': {'lat': -58, 'lng': 13},
    'Seattle, WA': {'lat': -54, 'lng': -35},
    'Irving, TX': {'lat': -65, 'lng': 0},
    'Washington, DC': {'lat': -30, 'lng': -40},
    'Atlanta, GA': {'lat': -2, 'lng': 12},
    'Kansas City, MO': {'lat': -64, 'lng': 37},
    'Phoenix, AZ': {'lat': -65, 'lng': -40},
    'Norfolk, VA': {'lat': -104, 'lng': 0},
    'Boise, ID': {'lat': -70, 'lng': -26},
    'Bakersfield, CA': {'lat': -27, 'lng': -55},
    'Reno, NV': {'lat': -88, 'lng': 43},
    'Houston, TX': {'lat': -46, 'lng': 9},
    'Chandler, AZ': {'lat': -99, 'lng': 38},
    'San Antonio, TX': {'lat': 6, 'lng': -31},
    'Henderson, NV': {'lat': -52, 'lng': -47},
    'Newark, NJ': {'lat': -10, 'lng': -11},
    'Winston Salem, NC': {'lat': -57, 'lng': 36},
    'Saint Louis, MO': {'lat': -106, 'lng': 43},
    'Oklahoma City, OK': {'lat': -77, 'lng': 30},
    'Chesapeake, VA': {'lat': -29, 'lng': -52},
    'Stockton, CA': {'lat': -106, 'lng': -66},
    'Corpus Christi, TX': {'lat': -25, 'lng': -26},
    'Boston, MA': {'lat': -124, 'lng': 6},
    'Garland, TX': {'lat': 2, 'lng': -6},
    'Anaheim, CA': {'lat': -31, 'lng': 14},
    'Memphis, TN': {'lat': -9, 'lng': 29},
    'Fort Worth, TX': {'lat': -25, 'lng': 28},
    'Omaha, NE': {'lat': -31, 'lng': 30},
    'San Diego, CA': {'lat': -36, 'lng': 39},
    'Birmingham, AL': {'lat': -39, 'lng': -53},
    'Detroit, MI': {'lat': -53, 'lng': 16},
    'Colorado Springs, CO': {'lat': -50, 'lng': 40},
    'Gilbert, AZ': {'lat': -70, 'lng': 31},
    'San Bernardino, CA': {'lat': -111, 'lng': -21},
    'Virginia Beach, VA': {'lat': -83, 'lng': -37},
    'Honolulu, HI': {'lat': -3, 'lng': 2},
    'Santa Ana, CA': {'lat': -124, 'lng': 32},
    'Plano, TX': {'lat': 0, 'lng': -55},
    'Indianapolis, IN': {'lat': -18, 'lng': -25},
    'Sacramento, CA': {'lat': -38, 'lng': 27},
    'Durham, NC': {'lat': -118, 'lng': 16},
    'Lincoln, NE': {'lat': -108, 'lng': 48},
    'Toledo, OH': {'lat': -44, 'lng': 44},
    'Dallas, TX': {'lat': -53, 'lng': 20},
    'Pittsburgh, PA': {'lat': -17, 'lng': 24},
    'Long Beach, CA': {'lat': -29, 'lng': -5},
    'Wichita, KS': {'lat': -17, 'lng': -41},
    'San Jose, CA': {'lat': -99, 'lng': -44},
    'San Francisco, CA': {'lat': -11, 'lng': -13},
    'Saint Petersburg, FL': {'lat': -120, 'lng': -11},
    'Baton Rouge, LA': {'lat': -77, 'lng': 22},
    'Philadelphia, PA': {'lat': -25, 'lng': -23},
    'Riverside, CA': {'lat': -90, 'lng': -26},
    'Louisville, KY': {'lat': -109, 'lng': -45},
    'Jersey City, NJ': {'lat': -49, 'lng': -22},
    'Columbus, OH': {'lat': -74, 'lng': -30},
    'Cincinnati, OH': {'lat': -4, 'lng': 45},
    'Portland, OR': {'lat': 25, 'lng': 11},
    'Buffalo, NY': {'lat': -80, 'lng': -29},
    'Lexington, KY': {'lat': -29, 'lng': -6},
    'Arlington, TX': {'lat': 19, 'lng': 25},
    'Cleveland, OH': {'lat': -6, 'lng': 10},
    'Charlotte, NC': {'lat': -57, 'lng': -15},
    'Glendale, AZ': {'lat': -32, 'lng': -38},
    'Tucson, AZ': {'lat': -53, 'lng': 21},
    'Raleigh, NC': {'lat': -116, 'lng': -12},
    'Madison, WI': {'lat': -100, 'lng': 10},
    'Irvine, CA': {'lat': 16, 'lng': -8},
    'New York, NY': {'lat': -77, 'lng': 9},
    'Lubbock, TX': {'lat': -90, 'lng': -18},
    'Baltimore, MD': {'lat': 21, 'lng': -3},
    'Saint Paul, MN': {'lat': -12, 'lng': 28},
    'Minneapolis, MN': {'lat': -105, 'lng': 15},
    'Fresno, CA': {'lat': 6, 'lng': 37},
    'Tampa, FL': {'lat': 23, 'lng': 24},
    'Las Vegas, NV': {'lat': -80, 'lng': 12},
    'Scottsdale, AZ': {'lat': -44, 'lng': 48},
    'Oakland, CA': {'lat': -2, 'lng': -56},
    'Los Angeles, CA': {'lat': -74, 'lng': -3},
    'Austin, TX': {'lat': -91, 'lng': 37},
    'Anchorage, AK': {'lat': -12, 'lng': 13},
    'Nashville, TN': {'lat': 20, 'lng': -65},
    'Miami, FL': {'lat': -71, 'lng': -27},
    'Chula Vista, CA': {'lat': -90, 'lng': -5},
    'New Orleans, LA': {'lat': -47, 'lng': 11},
    'Denver, CO': {'lat': -10, 'lng': -7},
    'Albuquerque, NM': {'lat': -22, 'lng': -62},
    'Aurora, CO': {'lat': -3, 'lng': 32},
    'Chicago, IL': {'lat': 15, 'lng': -3},
    'Mesa, AZ': {'lat': -2, 'lng': 42},
    'Jacksonville, FL': {'lat': 29, 'lng': -11},
    'North Las Vegas, NV': {'lat': -25, 'lng': 1},
    'Hialeah, FL': {'lat': -35, 'lng': -20},
    'Greensboro, NC': {'lat': -81, 'lng': -41},
    'Orlando, FL': {'lat': -51, 'lng': 15}
}